import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { currentAskEremiteContext } from '@/app/_lib/ask-eremite-context';

const params = values => ({ get: key => values[key] ?? null });
const id = '00000000-0000-4000-8000-000000000001';
const project = '00000000-0000-4000-8000-000000000002';
assert.deepEqual(currentAskEremiteContext('/inbox', params({})), { target: { kind: 'global' }, label: '全局' });
assert.deepEqual(currentAskEremiteContext('/inbox', params({ selected: id })), { target: { kind: 'content', id }, label: '当前资料' });
assert.deepEqual(currentAskEremiteContext(`/viewer/${id}`, params({})), { target: { kind: 'content', id }, label: '当前资料' });
assert.deepEqual(currentAskEremiteContext(`/projects/${project}`, params({})), { target: { kind: 'project', id: project }, label: '当前专案' });
assert.deepEqual(currentAskEremiteContext(`/projects/${project}`, params({ selected: id })), { target: { kind: 'content', id }, label: '当前资料' });
assert.deepEqual(currentAskEremiteContext('/actions', params({ selected: id })), { target: { kind: 'actions', id }, label: '行动台' });
assert.deepEqual(currentAskEremiteContext(`/projects/${project}`, params({ tab: 'actions' })), { target: { kind: 'actions', projectId: project }, label: '专案行动' });
const otherId = '00000000-0000-4000-8000-000000000003';
for (const pathname of ['/inbox', `/projects/${project}`]) {
  const selectedUrl = new URL(`http://localhost${pathname}?selected=${id}`);
  const before = currentAskEremiteContext(selectedUrl.pathname, selectedUrl.searchParams);
  assert.deepEqual(before.target, { kind: 'content', id });
  // New Conversation changes only the thread; context is derived afresh from the current URL.
  assert.deepEqual(currentAskEremiteContext(selectedUrl.pathname, selectedUrl.searchParams).target, before.target);
  selectedUrl.searchParams.set('selected', otherId);
  assert.deepEqual(currentAskEremiteContext(selectedUrl.pathname, selectedUrl.searchParams).target, { kind: 'content', id: otherId });
  selectedUrl.searchParams.delete('selected');
  assert.notDeepEqual(currentAskEremiteContext(selectedUrl.pathname, selectedUrl.searchParams).target, before.target);
}
assert.deepEqual(currentAskEremiteContext('/search', params({ selected: id })).target, { kind: 'global' }, 'navigation never reuses stale Content');

const component = await readFile('src/app/_components/ask-eremite.tsx', 'utf8');
const newChatBody = component.match(/async function newChat\(\) \{([\s\S]*?)\n  \}/u)?.[1];
assert.ok(newChatBody);
assert.doesNotMatch(newChatBody, /router\.|setContext|selected/u);
assert.match(component, /context: context\.target/u);
assert.match(component, /message\.activities\.length > 0 && <ActivityTrail/u);
assert.match(component, /running && toolTrail\.length > 0 && !detail\?\.messages\.some[\s\S]*<ActivityTrail activities=\{toolTrail\} live/u);
const styles = await readFile('src/app/styles.css', 'utf8');
assert.match(component, /message\.sources\.map/u);
assert.match(component, /<Link href=\{source\.href\}/u);
assert.match(component, /参考来源/u);
assert.match(component, /message\.actionDrafts\.map/u);
assert.match(component, /<strong>\{draft\.title\}<\/strong>/u);
assert.match(component, /message\.actionUpdates\.map/u);
assert.match(component, /message\.actionDisambiguations\.map/u);
assert.match(component, /choose_action_target/u);
assert.match(component, /请选择要修改的任务/u);
assert.match(component, /type="search"/u);
assert.match(component, /filtered\.slice\(0, visibleCount\)/u);
assert.match(component, /显示更多候选/u);
assert.match(component, /type="radio"/u);
assert.match(component, /item\.actionId\.slice\(-8\)/u);
assert.match(component, /item\.state === 'needs_input'/u);
assert.match(component, /apply_action_update/u);
assert.match(component, /reject_action_update/u);
assert.match(component, /row\.before/u);
assert.match(component, /row\.after/u);
assert.match(component, /after: patch\.title/u, 'Update card uses the persisted proposal title without adding punctuation');
assert.match(component, /confirm_action_draft/u);
assert.match(component, /reject_action_draft/u);
assert.match(component, /draft\.lifecycle === 'pending'/u);
assert.match(component, /刷新状态/u);
assert.match(component, /aria-busy=\{Boolean\(busy\)\}/u);
assert.match(component, /draftPending\.current = true/u);
assert.match(component, /正在创建任务/u);
assert.match(component, /创建任务/u);
assert.match(component, /查看任务/u);
assert.match(component, /onScroll=\{trackScroll\}/u);
assert.match(component, /!following &&/u);
assert.match(component, /prefers-reduced-motion/u);
assert.match(component, /onActivity: event/u);
assert.match(component, /activityFailureLabel\(item\)/u);
assert.match(component, /未能创建行动草稿/u);
assert.match(component, /存在多个可能的行动，请明确选择目标/u);
assert.match(component, /message\.error_code === 'ai_tool_call_invalid'/u);
assert.match(component, /message\.actionDrafts\.length > 0 \? `已创建/u);
assert.doesNotMatch(component, /activityDoneLabel/u);
assert.doesNotMatch(component, /rows=\{3\} disabled=\{busy\}/u);
assert.match(component, /role="status"/u);
assert.match(component, /role="alert"/u);
assert.match(styles, /@media \(max-width: 839px\)[\s\S]*\.ui-dialog\.ask-eremite-panel \{ inset: 0;/u);
assert.match(styles, /\.ask-sources a:focus-visible/u);
assert.match(styles, /\.ask-draft-card--stale/u);
assert.match(styles, /\.ask-update-card dl > div/u);
assert.match(styles, /\.ask-disambiguation-list[\s\S]*overflow-y: auto/u);
assert.match(styles, /@media \(max-width: 839px\)[\s\S]*\.ask-draft-card dl > div/u);
assert.match(styles, /@media \(prefers-reduced-motion: reduce\)/u);
console.log('Ask Eremite UI gate passed: context targets, separate Sources, Draft and Update cards, responsive diff and lifecycle states.');
